src/localshop/apps/accounts/urls.py
from django.conf.urls import include, url

from localshop.apps.accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^access-keys/$', views.AccessKeyListView.as_view(), name='access_key_list'),
    url(r'^access-keys/new$', views.AccessKeyCreateView.as_view(), name='access_key_create'),
    url(r'^access-keys/(?P<pk>\d+)/', include([
        url(r'^secret$', views.AccessKeySecretView.as_view(), name='access_key_secret'),
        url(r'^edit$', views.AccessKeyUpdateView.as_view(), name='access_key_edit'),
        url(r'^delete$', views.AccessKeyDeleteView.as_view(), name='access_key_delete'),
    ])),

    url(r'^teams/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^teams/create$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^teams/(?P<pk>\d+)/', include([
        url(r'^$', views.TeamDetailView.as_view(), name='team_detail'),
        url(r'^edit$', views.TeamUpdateView.as_view(), name='team_edit'),
        url(r'^delete$', views.TeamDeleteView.as_view(), name='team_delete'),
        url(r'^member-add$', views.TeamMemberAddView.as_view(), name='team_member_add'),
        url(r'^member-remove$', views.TeamMemberRemoveView.as_view(), name='team_member_remove'),
    ]))
]

src/localshop/apps/dashboard/urls.py
from django.conf.urls import include, url

from localshop.apps.dashboard import views

app_name = 'dashboard'

repository_urls = [
    # Package urls
    url(r'^packages/add/$',
        views.PackageAddView.as_view(),
        name='package_add'),
    url(r'^packages/(?P<name>[-._\w]+)/', include([
        url(r'^$',
            views.PackageDetailView.as_view(),
            name='package_detail'),
        url(r'^refresh-from-upstream/$',
            views.PackageRefreshView.as_view(),
            name='package_refresh'),
        url(r'^release-mirror-file/$',
            views.PackageMirrorFileView.as_view(),
            name='package_mirror_file'),
    ])),

    # CIDR
    url(r'^settings/cidr/$',
        views.CidrListView.as_view(), name='cidr_index'),
    url(r'^settings/cidr/create$',
        views.CidrCreateView.as_view(), name='cidr_create'),
    url(r'^settings/cidr/(?P<pk>\d+)/edit',
        views.CidrUpdateView.as_view(), name='cidr_edit'),
    url(r'^settings/cidr/(?P<pk>\d+)/delete',
        views.CidrDeleteView.as_view(), name='cidr_delete'),

    # Credentials
    url(r'^settings/credentials/$',
        views.CredentialListView.as_view(),
        name='credential_index'),
    url(r'^settings/credentials/create$',
        views.CredentialCreateView.as_view(),
        name='credential_create'),
    url(r'^settings/credentials/(?P<access_key>[-a-f0-9]+)/secret',
        views.CredentialSecretKeyView.as_view(),
        name='credential_secret'),
    url(r'^settings/credentials/(?P<access_key>[-a-f0-9]+)/edit',
        views.CredentialUpdateView.as_view(),
        name='credential_edit'),
    url(r'^settings/credentials/(?P<access_key>[-a-f0-9]+)/delete',
        views.CredentialDeleteView.as_view(),
        name='credential_delete'),

    url(r'^settings/teams/$', views.TeamAccessView.as_view(), name='team_access'),
]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^repositories/create$', views.RepositoryCreateView.as_view(), name='repository_create'),

    url(r'^repositories/(?P<slug>[^/]+)/', include([
        url(r'^$', views.RepositoryDetailView.as_view(), name='repository_detail'),
        url(r'^edit$', views.RepositoryUpdateView.as_view(), name='repository_edit'),
        url(r'^delete$', views.RepositoryDeleteView.as_view(), name='repository_delete'),
        url(r'^refresh$', views.RepositoryRefreshView.as_view(), name='repository_refresh'),
    ])),

    url(r'^repositories/(?P<repo>[^/]+)/', include(repository_urls))

]

src/localshop/urls.py
import re

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

import localshop.apps.dashboard.urls
import localshop.apps.packages.urls
from localshop import views
from localshop.apps.packages.views import SimpleIndex
from localshop.apps.packages.xmlrpc import handle_request

admin.autodiscover()

static_prefix = re.escape(settings.STATIC_URL.lstrip('/'))


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/', include(localshop.apps.dashboard.urls)),

    # Default path for xmlrpc calls
    url(r'^RPC2$', handle_request),
    url(r'^pypi$', handle_request),

    url(r'^repo/', include(localshop.apps.packages.urls)),

    # Backwards compatible url (except for POST requests)
    url(r'^simple/?$', SimpleIndex.as_view(), {'repo': 'default'}),
    url(r'^simple/(?P<path>.*)',
        RedirectView.as_view(url='/repo/default/%(path)s')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^accounts/', include('localshop.apps.accounts.auth_urls')),
    url(r'^accounts/', include('localshop.apps.accounts.urls')),
    url(r'^admin/', admin.site.urls),
]

src/localshop/templatetags/forms.py
from django import template

register = template.Library()


@register.filter
def form_widget(field):
    return field.field.widget.__class__.__name__

src/localshop/apps/accounts/views.py
from braces.views import UserFormKwargsMixin
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import SuspiciousOperation
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from localshop.apps.accounts import forms, models


class TeamListView(LoginRequiredMixin, generic.ListView):
    queryset = models.Team.objects.all()


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Team
    fields = ['description', 'name']
    template_name = 'accounts/team_form.html'

    def form_valid(self, form):
        team = form.save()
        team.members.create(user=self.request.user, role='owner')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'accounts:team_detail', kwargs={'pk': self.object.pk})


class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Team

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'form_member_add': forms.TeamMemberAddForm(team=self.object),
        })
        return ctx


class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = models.Team
    fields = ['description', 'name']
    template_name = 'accounts/team_form.html'

    def get_success_url(self):
        return reverse(
            'accounts:team_detail', kwargs={'pk': self.object.pk})


class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Team

    def get_success_url(self):
        return reverse('accounts:team_list')


class TeamMixin(object):
    def dispatch(self, request, pk):
        self.team = get_object_or_404(models.Team, pk=pk)
        return super().dispatch(request, pk)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['team'] = self.team
        return kwargs


class TeamMemberAddView(LoginRequiredMixin, TeamMixin, generic.FormView):
    http_method_names = ['post']
    form_class = forms.TeamMemberAddForm

    def form_valid(self, form):
        form.save()
        return redirect('accounts:team_detail', pk=self.team.pk)

    def form_invalid(self, form):
        return redirect('accounts:team_detail', pk=self.team.pk)


class TeamMemberRemoveView(LoginRequiredMixin, TeamMixin, generic.FormView):
    http_method_names = ['post']
    form_class = forms.TeamMemberRemoveForm

    def form_valid(self, form):
        form.cleaned_data['member_obj'].delete()
        return redirect('accounts:team_detail', pk=self.team.pk)

    def form_invalid(self, form):
        return redirect('accounts:team_detail', pk=self.team.pk)


class ProfileView(LoginRequiredMixin, generic.FormView):
    form_class = forms.ProfileForm
    template_name = 'accounts/profile.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('accounts:profile')


class AccessKeyListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'access_keys'

    def get_queryset(self):
        return self.request.user.access_keys.all()


class AccessKeyCreateView(LoginRequiredMixin, UserFormKwargsMixin,
                          generic.CreateView):
    template_name = 'accounts/accesskey_form.html'
    form_class = forms.AccessKeyForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_queryset(self):
        return self.request.user.access_keys.all()

    def get_success_url(self):
        return reverse('accounts:access_key_list')


class AccessKeySecretView(LoginRequiredMixin, generic.DetailView):

    def get_queryset(self):
        return self.request.user.access_keys.all()

    def get(self, request, pk, *args, **kwargs):
        if not request.is_ajax():
            raise SuspiciousOperation
        key = get_object_or_404(self.request.user.access_keys, pk=pk)
        return HttpResponse(key.secret_key)


class AccessKeyUpdateView(LoginRequiredMixin, UserFormKwargsMixin,
                          generic.UpdateView):
    template_name = 'accounts/accesskey_form.html'
    form_class = forms.AccessKeyForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_queryset(self):
        return self.request.user.access_keys.all()

    def get_success_url(self):
        return reverse('accounts:access_key_list')


class AccessKeyDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'accounts/accesskey_confirm_delete.html'
    context_object_name = 'access_key'

    def get_queryset(self):
        return self.request.user.access_keys.all()

    def get_success_url(self):
        return reverse('accounts:access_key_list')


@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='registration/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=forms.AuthenticationForm,
          current_app=None, extra_context=None):
    """Displays the login form and handles the login action.

    Copy from Django source code, added ability to set remember_me

    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, allowed_hosts=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)

src/localshop/apps/dashboard/views/cidr.py
from django.urls import reverse
from django.views import generic

from localshop.apps.dashboard import forms
from localshop.apps.dashboard.views.repository import RepositoryMixin

__all__ = [
    'CidrListView',
    'CidrCreateView',
    'CidrUpdateView',
    'CidrDeleteView',
]


class CidrListView(RepositoryMixin, generic.ListView):
    object_context_name = 'cidrs'
    template_name = 'dashboard/repository_settings/cidr_list.html'

    def get_queryset(self):
        return self.repository.cidr_list.all()


class CidrCreateView(RepositoryMixin, generic.CreateView):
    form_class = forms.AccessControlForm
    template_name = 'dashboard/repository_settings/cidr_form.html'

    def get_success_url(self):
        return reverse('dashboard:cidr_index', kwargs={
            'repo': self.repository.slug,
        })

    def get_queryset(self):
        return self.repository.cidr_list.all()


class CidrUpdateView(RepositoryMixin, generic.UpdateView):
    form_class = forms.AccessControlForm
    template_name = 'dashboard/repository_settings/cidr_form.html'

    def get_success_url(self):
        return reverse('dashboard:cidr_index', kwargs={
            'repo': self.repository.slug,
        })

    def get_queryset(self):
        return self.repository.cidr_list.all()


class CidrDeleteView(RepositoryMixin, generic.DeleteView):
    form_class = forms.AccessControlForm
    template_name = 'dashboard/repository_settings/cidr_confirm_delete.html'

    def get_success_url(self):
        return reverse('dashboard:cidr_index', kwargs={
            'repo': self.repository.slug,
        })

    def get_queryset(self):
        return self.repository.cidr_list.all()

src/localshop/apps/dashboard/views/credentials.py
from django.contrib.sites.models import Site
from django.core.exceptions import SuspiciousOperation
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views import generic

from localshop.apps.dashboard import forms
from localshop.apps.dashboard.views.repository import RepositoryMixin

__all__ = [
    'CredentialListView',
    'CredentialCreateView',
    'CredentialSecretKeyView',
    'CredentialUpdateView',
    'CredentialDeleteView',
]


class CredentialListView(RepositoryMixin, generic.ListView):
    object_context_name = 'credentials'
    template_name = 'dashboard/repository_settings/credential_list.html'

    def get_queryset(self):
        return self.repository.credentials.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_url'] = Site.objects.get_current()
        return context


class CredentialCreateView(RepositoryMixin, generic.CreateView):
    form_class = forms.CredentialModelForm
    template_name = 'dashboard/repository_settings/credential_form.html'

    def get_queryset(self):
        return self.repository.credentials.all()

    def get_success_url(self):
        return reverse('dashboard:credential_index', kwargs={
            'repo': self.repository.slug,
        })


class CredentialSecretKeyView(RepositoryMixin, generic.View):

    def get(self, request, repo, access_key):
        if not request.is_ajax():
            raise SuspiciousOperation
        credential = get_object_or_404(
            self.repository.credentials, access_key=access_key)
        return HttpResponse(credential.secret_key)


class CredentialUpdateView(RepositoryMixin, generic.UpdateView):
    form_class = forms.CredentialModelForm
    slug_field = 'access_key'
    slug_url_kwarg = 'access_key'
    template_name = 'dashboard/repository_settings/credential_form.html'

    def get_queryset(self):
        return self.repository.credentials.all()

    def get_success_url(self):
        return reverse('dashboard:credential_index', kwargs={
            'repo': self.repository.slug,
        })


class CredentialDeleteView(RepositoryMixin, generic.DeleteView):
    slug_field = 'access_key'
    slug_url_kwarg = 'access_key'

    def get_success_url(self):
        return reverse('dashboard:credential_index', kwargs={
            'repo': self.repository.slug,
        })

src/localshop/views.py
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt

from localshop.apps.packages import xmlrpc


@csrf_exempt
def index(request):
    if request.method == 'POST':
        return xmlrpc.handle_request(request)
    return redirect('dashboard:index')

src/localshop/templates/dashboard/index.html
{% extends "layout.main.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Repositories
                    <div class="btn-group pull-right">
                        <a href="{% url 'dashboard:repository_create' %}" class="btn btn-success btn-xs">
                            <span class="icon-plus icon-white"></span> Create new
                        </a>
                    </div>
                </div>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for repository in repositories %}
                        <tr>
                            <td><a href="{% url 'dashboard:repository_detail' slug=repository.slug %}">{{ repository.name }}</a></td>
                            <td>{{ repository.description }}</td>
                            <td>
                                {% if repository.enable_auto_mirroring %}
                                <a href="{% url 'dashboard:repository_refresh' slug=repository.slug %}" class="btn btn-success btn-xs">
                                    Refresh
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Teams
                    {% if user.is_superuser %}
                    <a href="{% url 'accounts:team_list' %}" class="pull-right">
                        <i class="glyphicon glyphicon-cog"></i>
                    </a>
                    {% endif %}
                </div>
                <ul class="list-group">
                    {% for member in user.team_memberships.all %}
                    <li class="list-group-item">
                        {% if member.is_owner %}
                        <a href="{{ member.team.get_absolute_url }}">
                            <i class="glyphicon glyphicon-tent"></i>
                            {{ member.team }}
                        </a>
                        {% else %}
                        <i class="glyphicon glyphicon-tent"></i>
                        {{ member.team }}
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

src/localshop/templates/dashboard/package_detail.html
{% extends "dashboard/repository_settings/base.html" %}
{% load i18n %}

{% block title %}
<a href="{% url 'dashboard:repository_detail' slug=package.repository.slug %}">{{ package.repository.simple_index_url }}</a>/{{ package.name }}
{% endblock %}


{% block description %}
{{ release.summary }}
{% endblock %}

{% block content_panel %}
<div class="tabbable">
    <ul class="nav nav-tabs" id="package-tabs">
        <li class="active">
            <a href="#information" data-toggle="tab">Metadata</a>
        </li>
        <li><a href="#description" data-toggle="tab">Readme</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="description">
            <div class="row">
                <div class="col-md-9">
                    {{ release.description_html|safe }}
                </div>
            </div>
        </div>
        <div class="tab-pane active" id="information">

            <div class="row">
                <div class="col-md-7">
                    {% if package.is_local %}
                    <h2>Owners</h2>
                    <p>The following users are owners of this local package</p>
                    <ul>
                        {% for user in package.owners.all %}
                        <li>{{ user.username }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <h2>Metadata</h2>
                    <table class="table table-striped table-condensed table-bordered">
                        <tbody>
                            <tr>
                                <td>Version</td>
                                <td>{{ release.version }}</td>
                            </tr>
                            <tr>
                                <td>License</td>
                                <td>{{ release.license }}</td>
                            </tr>
                            <tr>
                                <td>Author</td>
                                <td>{{ release.author }} &lt;{{ release.author_email }}&gt;</td>
                            </tr>
                            <tr>
                                <td>Homepage</td>
                                <td><a href="{{ release.home_page}}">{{ release.home_page }}</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-2">
                    <h2>Info</h2>
                    {% if package.is_local %}
                    <p>
                    This is a local package and only
                    available from this shop.
                    </p>
                    <span class="btn" disabled="disabled"><span class="icon-refresh"></span> Refresh</span>
                    {% else %}
                    Upstream information:
                    <ul>
                        <li><a href="{{ pypi_url }}/{{ package.name }}">pypi</a></li>
                    </ul>

                    <a href="{% url 'dashboard:package_refresh' repo=view.repository.slug name=package.name %}" class="btn btn-primary btn-small"><span class="icon-refresh"></span> Refresh</a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <h2>Files</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th colspan="2">Filename</th>
                                <th>Type</th>
                                <th>MD5 digest</th>
                                <th>Released</th>
                                <th>Python</th>
                                <th>Labels</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for release in package.releases.all %}
                            <tr>
                                <th colspan="8">{{ release.version }}</th>
                            </tr>
                                {% for file in release.files.all %}
                            <tr>
                                <td>&nbsp;</td>
                                <td><a href="{{ file.get_absolute_url }}">{{ file.filename }}</a></td>
                                <td>{{ file.get_filetype_display }}</td>
                                <td>{{ file.md5_digest }}</td>
                                <td>{{ file.created }}</td>
                                <td>{{ file.python_version }}</td>
                                <td>
                                    {% if file.distribution %}
                                    <span class="label label-success">local copy</span>
                                    {% else %}
                                    <form method="post" action="{% url 'dashboard:package_mirror_file' repo=package.repository.slug name=package.name %}">
                                        <input type="hidden" name="pk" value="{{ file.pk }}">
                                        <button type="submit" class="btn btn-primary btn-xs">mirror</button>
                                        {% csrf_token %}
                                    </form>
                                    {% endif %}
                                </td>
                            </tr>
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/localshop/templates/dashboard/repository_create.html
{% extends "layout.main.html" %}
{% load i18n %}


{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            Create repository
        </div>
        <div class="panel-body">
            <form method="post" action="" class="form-stacked">
                <fieldset>
                    {% include "partial/_form_fields.html" %}
                </fieldset>

                <div class="form-actions">
                    <button type="submit" class="btn btn-primary"><span class="icon-ok icon-white"></span> Save</button>
                    <a href="{% url 'dashboard:index' %}" class="btn">Cancel</a>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

src/localshop/templates/dashboard/repository_detail.html
{% extends "dashboard/repository_settings/base.html" %}
{% load humanize %}
{% load i18n %}

{% block content_panel %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="pull-left">Repository index</span>
            <form class="form-inline" method="post" action="{% url 'dashboard:package_add' repo=view.repository.slug %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="name">
                    <button type="submit" class="btn btn-primary btn-xs">Lookup</button>
                </div>
                {% csrf_token %}
            </form>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Last update</th>
                </tr>
            </thead>
            <tbody>
                {% for package in repository.packages.all %}
                <tr>
                    <td><a href="{% url 'dashboard:package_detail' repo=repository.slug name=package.name %}">{{ package.name }}</a></td>
                    <td>
                        {% if package.is_local %}
                        local package
                        {% else %}
                        pypi package
                        {% endif %}
                    </td>
                    <td>{{ package.update_timestamp|naturaltime }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}